---

name: MobileNet-SSD
gops: 2.3

time: true

model: $(home)/MobileNetSSD_deploy.prototxt
weight: $(home)/MobileNetSSD_deploy.caffemodel
input_shapes: "[1,3,300,300]"
batch_sizes: [1, 4, 8, 16]

int8_model: $(workdir)/$(name)_bmnetc_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmnetc.int8umodel

BM1684:
  fp_loops:
    - build_env:
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      opt: "1"
      dyn: "False"
      fp_outdir_template: "static.opt1.fp32.{}b.compilation"
      prec: FP32
    - build_env:
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      opt: "2"
      dyn: "True"
      fp_outdir_template: "dynamic.opt2.fp32.{}b.compilation"
      prec: FP32

BM1684X:
  fp_loops:
    - build_env:
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      opt: "1"
      dyn: "False"
      fp_outdir_template: "static.opt1.fp32.{}b.compilation"
      prec: FP32
    - build_env:
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      opt: "2"
      dyn: "True"
      fp_outdir_template: "dynamic.opt2.fp32.{}b.compilation"
      prec: FP32

int8_loops:
  - build_env:
      - BMCOMPILER_GROUP_SEARCH_COUNT=1
    opt: "1"
    dyn: "False"
    int8_outdir_template: "static.opt1.int8.{}b.compilation"
  - build_env:
      - BMCOMPILER_GROUP_SEARCH_COUNT=1
    opt: "2"
    dyn: "True"
    int8_outdir_template: "dynamic.opt2.int8.{}b.compilation"

fp_batch_sizes: $(batch_sizes)

fp_compile_options:
  bmnetc
    --model $(model)
    --weight $(weight)
    --shapes $(input_shapes)
    --net_name $(name)
    --target $(target)
    --enable_profile true

time_only_cali:
  python3 -m ufw.cali.cali_model
    --model $(model)
    --weight $(weight)
    --input_shapes $(input_shapes)
    --net_name $(name)
    --cali_iteration 1
    --target $(target)
    --test_iterations 1
    --debug_cmd "not_call_bmnetu;not_suspend;use_fake_data_to_test"

bmnetu_batch_sizes: $(batch_sizes)

bmnetu_options:
  --model $(int8_model)
  --weight $(int8_weight)
  --target $(target)
  --enable_profile True
